/** Dados iniciais locais que não dependem do conteúdo bíblico compartilhado. */

import { QuizQuestion } from './db';

export const initialQuizQuestions: QuizQuestion[] = [
  { question: 'Quem construiu a arca?', options: ['Moisés', 'Noé', 'Abraão', 'Davi'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quantos discípulos Jesus teve?', options: ['10', '11', '12', '13'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual o menor livro da Bíblia?', options: ['Judas', '3 João', '2 João', 'Filemom'], correctIndex: 2, category: 'Geral', difficulty: 'medium', points: 15 },
  { question: 'Quem matou Golias?', options: ['Saul', 'Davi', 'Josué', 'Sansão'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quantos livros tem a Bíblia?', options: ['64', '66', '72', '73'], correctIndex: 1, category: 'Geral', difficulty: 'easy', points: 10 },
  { question: 'Quem foi jogado na cova dos leões?', options: ['Jonas', 'Daniel', 'Elias', 'Jeremias'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Em que cidade Jesus nasceu?', options: ['Nazaré', 'Jerusalém', 'Belém', 'Cafarnaum'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem batizou Jesus?', options: ['Pedro', 'João Batista', 'Paulo', 'Tiago'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual era a profissão de Paulo antes de ser apóstolo?', options: ['Pescador', 'Carpinteiro', 'Fabricante de tendas', 'Cobrador de impostos'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quantos dias Jesus ficou no deserto?', options: ['7', '30', '40', '50'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual o primeiro livro da Bíblia?', options: ['Êxodo', 'Gênesis', 'Salmos', 'Mateus'], correctIndex: 1, category: 'Geral', difficulty: 'easy', points: 10 },
  { question: 'Quem foi o primeiro rei de Israel?', options: ['Davi', 'Salomão', 'Saul', 'Samuel'], correctIndex: 2, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual apóstolo negou Jesus três vezes?', options: ['João', 'Judas', 'Pedro', 'Tomé'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quantas pragas Deus enviou ao Egito?', options: ['5', '7', '10', '12'], correctIndex: 2, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem escreveu a maioria dos Salmos?', options: ['Moisés', 'Salomão', 'Davi', 'Asafe'], correctIndex: 2, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual o último livro da Bíblia?', options: ['Judas', 'Apocalipse', 'Malaquias', '3 João'], correctIndex: 1, category: 'Geral', difficulty: 'easy', points: 10 },
  { question: 'Quem traiu Jesus por 30 moedas de prata?', options: ['Pedro', 'Tomé', 'Judas Iscariotes', 'Bartolomeu'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual o fruto proibido no Jardim do Éden, segundo a tradição?', options: ['Uva', 'Maçã', 'Figo', 'A Bíblia não especifica'], correctIndex: 3, category: 'Antigo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Quem foi levado ao céu em um carro de fogo?', options: ['Moisés', 'Enoque', 'Elias', 'Eliseu'], correctIndex: 2, category: 'Antigo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Quantos anos os israelitas vagaram no deserto?', options: ['20', '30', '40', '50'], correctIndex: 2, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual instrumento Davi tocava?', options: ['Flauta', 'Harpa', 'Trombeta', 'Tambor'], correctIndex: 1, category: 'Músicas', difficulty: 'easy', points: 10 },
  { question: 'Quem cantou após cruzar o Mar Vermelho?', options: ['Moisés', 'Miriã', 'Arão', 'Josué'], correctIndex: 1, category: 'Músicas', difficulty: 'medium', points: 15 },
  { question: 'Paulo e Silas cantaram na prisão. Onde estavam presos?', options: ['Roma', 'Jerusalém', 'Filipos', 'Corinto'], correctIndex: 2, category: 'Músicas', difficulty: 'hard', points: 20 },
  { question: 'Qual sinal Deus colocou como aliança após o dilúvio?', options: ['Uma estrela', 'O arco-íris', 'Uma nuvem', 'Uma pomba'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem foi o filho de Abraão com Sara?', options: ['Ismael', 'Isaque', 'Jacó', 'Esaú'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual era o nome dado a Jacó após lutar com Deus?', options: ['Judá', 'Israel', 'Efraim', 'Manassés'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem era o irmão de Moisés?', options: ['Josué', 'Arão', 'Calebe', 'Samuel'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem sucedeu Moisés na liderança de Israel?', options: ['Arão', 'Josué', 'Calebe', 'Samuel'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual cidade teve seus muros derrubados após o povo rodeá-la?', options: ['Jerusalém', 'Jericó', 'Betel', 'Hebrom'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem era a sogra de Rute?', options: ['Raquel', 'Noemi', 'Miriã', 'Débora'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual era o nome da mãe do profeta Samuel?', options: ['Ana', 'Marta', 'Ester', 'Mical'], correctIndex: 0, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'O que Salomão pediu a Deus?', options: ['Riquezas', 'Longa vida', 'Sabedoria', 'Vitória militar'], correctIndex: 2, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem visitou Salomão para provar sua sabedoria?', options: ['A rainha de Sabá', 'A rainha do Egito', 'Rute', 'Ester'], correctIndex: 0, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Contra quais profetas Elias enfrentou um desafio no monte Carmelo?', options: ['Profetas de Baal', 'Profetas de Aserá', 'Profetas de Dagom', 'Profetas de Moloque'], correctIndex: 0, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem foi curado de lepra após mergulhar no rio Jordão?', options: ['Naamã', 'Gehazi', 'Elias', 'Uzias'], correctIndex: 0, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem se tornou rainha e intercedeu pelo povo judeu?', options: ['Rute', 'Ester', 'Débora', 'Miriã'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem liderou a reconstrução dos muros de Jerusalém?', options: ['Esdras', 'Neemias', 'Zorobabel', 'Ageu'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual era o nome do filho de Davi que se tornou rei depois dele?', options: ['Absalão', 'Salomão', 'Amnom', 'Natã'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Para qual cidade Jonas foi enviado para anunciar uma mensagem?', options: ['Nínive', 'Társis', 'Babilônia', 'Damasco'], correctIndex: 0, category: 'Antigo Testamento', difficulty: 'easy', points: 10 },
  { question: 'O que Isaías viu no templo quando recebeu sua visão?', options: ['A arca aberta', 'O Senhor assentado no trono', 'Um anjo com uma espada', 'O rio Jordão'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Quais três homens foram lançados na fornalha ardente?', options: ['Pedro, Tiago e João', 'Sadraque, Mesaque e Abede-Nego', 'Caim, Abel e Sete', 'Moisés, Arão e Josué'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem interpretou os sonhos do rei Nabucodonosor?', options: ['Daniel', 'Ezequiel', 'Jeremias', 'Esdras'], correctIndex: 0, category: 'Antigo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual profeta foi alimentado por corvos junto ao ribeiro de Querite?', options: ['Eliseu', 'Elias', 'Isaías', 'Amós'], correctIndex: 1, category: 'Antigo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Quem foi o pai de João Batista?', options: ['Zacarias', 'Simeão', 'Joaquim', 'Nicodemos'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual anjo anunciou a Maria o nascimento de Jesus?', options: ['Miguel', 'Gabriel', 'Rafael', 'Uriel'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Para onde José levou Jesus e Maria para protegê-lo de Herodes?', options: ['Síria', 'Egito', 'Galileia', 'Samaria'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Onde Jesus realizou seu primeiro milagre, segundo o Evangelho de João?', options: ['Jerusalém', 'Caná da Galileia', 'Nazaré', 'Betânia'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual foi o primeiro milagre de Jesus registrado no Evangelho de João?', options: ['Multiplicar pães', 'Transformar água em vinho', 'Curar um cego', 'Acalmar a tempestade'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem eram as irmãs de Lázaro?', options: ['Marta e Maria', 'Maria e Salomé', 'Joana e Susana', 'Priscila e Febe'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual era o nome do cobrador de impostos que subiu em uma árvore para ver Jesus?', options: ['Mateus', 'Zaqueu', 'Jairo', 'Bartimeu'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem contou a parábola do bom samaritano?', options: ['Pedro', 'Jesus', 'Paulo', 'João Batista'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual discípulo afirmou que precisava ver para crer na ressurreição?', options: ['Pedro', 'Tomé', 'André', 'Filipe'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem ajudou a carregar a cruz de Jesus?', options: ['José de Arimateia', 'Simão de Cirene', 'Nicodemos', 'Bartimeu'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual mulher é citada como testemunha da ressurreição e encontrou o túmulo vazio?', options: ['Marta', 'Maria Madalena', 'Isabel', 'Lídia'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'O que aconteceu aos discípulos no dia de Pentecostes?', options: ['Receberam o Espírito Santo', 'Foram levados ao deserto', 'Construíram o templo', 'Partiram para Roma'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quem foi apedrejado e é reconhecido como o primeiro mártir cristão?', options: ['Estêvão', 'Tiago', 'Barnabé', 'Silas'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Para qual cidade Saulo estava indo quando teve seu encontro com Jesus?', options: ['Roma', 'Damasco', 'Antioquia', 'Jerusalém'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual era a profissão de Lídia, uma das primeiras convertidas na Europa?', options: ['Vendedora de púrpura', 'Pescadora', 'Carpinteira', 'Agricultora'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Quem teve uma visão de um lençol com animais e entendeu que Deus não faz acepção de pessoas?', options: ['Pedro', 'Paulo', 'João', 'Filipe'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Em qual ilha Paulo chegou após um naufrágio?', options: ['Creta', 'Malta', 'Chipre', 'Patmos'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Quem escreveu que viu a revelação registrada no Apocalipse?', options: ['João', 'Pedro', 'Paulo', 'Lucas'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual é o primeiro fruto do Espírito listado em Gálatas?', options: ['Alegria', 'Amor', 'Paz', 'Fé'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual peça da armadura de Deus é associada à fé?', options: ['O escudo', 'A espada', 'O capacete', 'O cinturão'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Como começa a oração ensinada por Jesus aos discípulos?', options: ['Senhor, eu agradeço', 'Pai nosso, que estás nos céus', 'Deus eterno, ouve-nos', 'Santo Deus, recebe'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual foi a reação de Jesus diante da morte de Lázaro?', options: ['Jesus chorou', 'Jesus fugiu', 'Jesus jejuou', 'Jesus dormiu'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Quantos cestos de pedaços sobraram após Jesus alimentar cinco mil pessoas?', options: ['5', '7', '10', '12'], correctIndex: 3, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Com quantos pães Jesus alimentou cerca de cinco mil homens?', options: ['2', '5', '7', '12'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Com quantos pães Jesus alimentou cerca de quatro mil pessoas?', options: ['5', '7', '10', '12'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'O que Jesus respondeu quando perguntaram sobre pagar impostos a César?', options: ['Não paguem impostos', 'Dai a César o que é de César', 'Paguem apenas no templo', 'Deixem a decisão para Pilatos'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Segundo Jesus, qual é o maior mandamento?', options: ['Guardar o sábado', 'Amar a Deus de todo o coração', 'Oferecer sacrifícios', 'Jejuar toda semana'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual mandamento Jesus chamou de semelhante ao primeiro?', options: ['Amar o próximo como a si mesmo', 'Não matar', 'Honrar os pais', 'Dar esmolas'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual novo mandamento Jesus deu aos seus discípulos?', options: ['Jejuem sempre', 'Amai-vos uns aos outros', 'Construam um templo', 'Guardem silêncio'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual parábola fala de um filho que voltou para casa depois de desperdiçar sua herança?', options: ['O semeador', 'O filho pródigo', 'A ovelha perdida', 'O bom samaritano'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual discípulo era conhecido por trabalhar como cobrador de impostos?', options: ['Mateus', 'Tiago', 'André', 'Judas'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem pediu o corpo de Jesus a Pilatos?', options: ['José de Arimateia', 'Simão de Cirene', 'Gamaliel', 'Cornélio'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual apóstolo foi irmão de Pedro?', options: ['André', 'Filipe', 'Bartolomeu', 'Mateus'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
  { question: 'Qual apóstolo era irmão de João e filho de Zebedeu?', options: ['Tiago', 'Tomé', 'Mateus', 'Simão, o Zelote'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual evangelista era médico?', options: ['Mateus', 'Marcos', 'Lucas', 'João'], correctIndex: 2, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Quem foi escolhido para ocupar o lugar de Judas Iscariotes entre os apóstolos?', options: ['Matias', 'Barnabé', 'Silas', 'Apolo'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Qual casal mentiu sobre o valor da oferta e morreu após ser confrontado?', options: ['Áquila e Priscila', 'Ananias e Safira', 'Herodes e Herodias', 'Zacarias e Isabel'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Qual centurião recebeu Pedro em sua casa e se converteu?', options: ['Cornélio', 'Júlio', 'Cláudio', 'Longino'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Em qual cidade os discípulos foram chamados cristãos pela primeira vez?', options: ['Antioquia', 'Jerusalém', 'Éfeso', 'Corinto'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'hard', points: 20 },
  { question: 'Qual carta apresenta a descrição do amor que é paciente e bondoso?', options: ['Romanos', '1 Coríntios', 'Efésios', 'Hebreus'], correctIndex: 1, category: 'Novo Testamento', difficulty: 'medium', points: 15 },
  { question: 'Qual livro registra principalmente as viagens e a obra dos apóstolos após a ressurreição?', options: ['Atos dos Apóstolos', 'Hebreus', 'Apocalipse', 'Romanos'], correctIndex: 0, category: 'Novo Testamento', difficulty: 'easy', points: 10 },
];
