export const permissionOptions = [
  { id: 'members:view', label: 'Membros: ver' },
  { id: 'members:create', label: 'Membros: criar' },
  { id: 'members:update', label: 'Membros: editar' },
  { id: 'members:delete', label: 'Membros: excluir' },
  { id: 'members:approve', label: 'Membros: aprovar' },
  { id: 'members:manage_access', label: 'Membros: acessos' },
  { id: 'groups:update', label: 'Grupos: editar' },
  { id: 'tasks:create', label: 'Tarefas: criar' },
  { id: 'tasks:update', label: 'Tarefas: editar' },
  { id: 'materials:view', label: 'Materiais: ver' },
  { id: 'materials:create', label: 'Materiais: criar' },
  { id: 'materials:update', label: 'Materiais: editar' },
  { id: 'materials:manage', label: 'Materiais: administrar' },
  { id: 'canteen:view', label: 'Cantina: ver' },
  { id: 'canteen:catalog', label: 'Cantina: catálogo' },
  { id: 'canteen:order', label: 'Cantina: pedir' },
  { id: 'canteen:manage', label: 'Cantina: administrar' },
  { id: 'canteen:create', label: 'Cantina: criar' },
  { id: 'canteen:operate', label: 'Cantina: operar' },
  { id: 'canteen:sell', label: 'Cantina: vender' },
  { id: 'canteen:manage_products', label: 'Cantina: produtos' },
  { id: 'feed:view', label: 'Feed: ver' },
  { id: 'feed:create', label: 'Feed: publicar' },
  { id: 'feed:publish', label: 'Feed: publicar avisos' },
  { id: 'feed:share', label: 'Feed: compartilhar' },
  { id: 'feed:comment', label: 'Feed: comentar' },
  { id: 'feed:update', label: 'Feed: editar' },
  { id: 'bible:view', label: 'Bíblia: ver' },
  { id: 'pastoral:view', label: 'Pastoral: ver' },
  { id: 'settings:update', label: 'Configurações: editar' },
] as const;
