import {
  Search,
  Skull,
  HelpCircle,
  BookOpen,
  Brain,
  Puzzle,
  Clock,
  CheckCircle,
  Grid3X3,
  BookMarked,
  Zap,
  Smile,
  Shuffle,
  Link,
  ScrollText,
  Crown,
  Hash,
  Swords,
  PersonStanding,
  Ship,
  Bomb,
  Target,
  Waves,
  Castle,
  Bug,
  Flame,
  BombIcon,
} from "lucide-react";

export const gamesCatalog = [
  { id: "caca-palavras", name: "Caça-Palavras", emoji: "🔍", icon: Search, color: "from-blue-600 to-blue-800", desc: "Encontre palavras bíblicas" },
  { id: "forca", name: "Jogo da Forca", emoji: "🐋", icon: Skull, color: "from-teal-600 to-teal-800", desc: "Adivinhe a palavra" },
  { id: "quem-sou-eu", name: "Quem Sou Eu?", emoji: "🤔", icon: HelpCircle, color: "from-amber-600 to-amber-800", desc: "Adivinhe o personagem" },
  { id: "quiz", name: "Quiz Bíblico", emoji: "📖", icon: BookOpen, color: "from-purple-600 to-purple-800", desc: "Teste seu conhecimento" },
  { id: "memoria", name: "Jogo da Memória", emoji: "🧠", icon: Brain, color: "from-rose-600 to-rose-800", desc: "Encontre os pares" },
  { id: "complete-versiculo", name: "Complete o Versículo", emoji: "✍️", icon: Puzzle, color: "from-green-600 to-green-800", desc: "Complete a passagem" },
  { id: "ordem-cronologica", name: "Ordem Cronológica", emoji: "⏳", icon: Clock, color: "from-orange-600 to-orange-800", desc: "Ordene os eventos" },
  { id: "verdadeiro-falso", name: "Verdadeiro ou Falso", emoji: "✅", icon: CheckCircle, color: "from-indigo-600 to-indigo-800", desc: "Julgue as afirmações" },
  { id: "palavras-cruzadas", name: "Palavras Cruzadas", emoji: "📝", icon: Grid3X3, color: "from-cyan-600 to-cyan-800", desc: "Preencha a grade" },
  { id: "adivinhe-livro", name: "Adivinhe o Livro", emoji: "📚", icon: BookMarked, color: "from-pink-600 to-pink-800", desc: "Qual livro da Bíblia?" },
  { id: "trivia-rapida", name: "Trivia Rápida", emoji: "⚡", icon: Zap, color: "from-yellow-600 to-yellow-800", desc: "10 segundos por pergunta!" },
  { id: "emoji-biblico", name: "Emoji Bíblico", emoji: "😀", icon: Smile, color: "from-emerald-600 to-emerald-800", desc: "Adivinhe pela emoji" },
  { id: "versiculo-embaralhado", name: "Versículo Embaralhado", emoji: "🔀", icon: Shuffle, color: "from-violet-600 to-violet-800", desc: "Ordene as palavras" },
  { id: "conecte-pares", name: "Conecte os Pares", emoji: "🔗", icon: Link, color: "from-sky-600 to-sky-800", desc: "Ligue os correspondentes" },
  { id: "parabolas", name: "Parábolas de Jesus", emoji: "📜", icon: ScrollText, color: "from-lime-600 to-lime-800", desc: "Identifique a parábola" },
  { id: "reis-profetas", name: "Reis ou Profetas", emoji: "👑", icon: Crown, color: "from-fuchsia-600 to-fuchsia-800", desc: "Classifique os personagens" },
  { id: "numeros-biblia", name: "Números da Bíblia", emoji: "🔢", icon: Hash, color: "from-red-600 to-red-800", desc: "Acerte os números bíblicos" },
  { id: "batalha-biblica", name: "Batalha Bíblica", emoji: "⚔️", icon: Swords, color: "from-red-700 to-rose-900", desc: "Combate por turnos épico!" },
  { id: "fuga-egito", name: "Fuga do Egito", emoji: "🏃", icon: PersonStanding, color: "from-amber-700 to-orange-900", desc: "Corra e desvie do Faraó!" },
  { id: "arca-noe", name: "Arca de Noé", emoji: "🚢", icon: Ship, color: "from-cyan-700 to-blue-900", desc: "Salve os animais a tempo!" },
  { id: "quiz-bomba", name: "Quiz Bomba", emoji: "💣", icon: Bomb, color: "from-orange-700 to-red-900", desc: "Errou = BOOM! 💥" },
  { id: "funda-davi", name: "Funda de Davi", emoji: "🪨", icon: Target, color: "from-stone-600 to-stone-800", desc: "Acerte os inimigos!" },
  { id: "travessia-mar", name: "Travessia do Mar", emoji: "🌊", icon: Waves, color: "from-blue-700 to-indigo-900", desc: "Atravesse o Mar Vermelho!" },
  { id: "muralhas-jerico", name: "Muralhas de Jericó", emoji: "🏰", icon: Castle, color: "from-amber-800 to-yellow-900", desc: "Repita e destrua!" },
  { id: "pragas-egito", name: "Pragas do Egito", emoji: "🏺", icon: Bug, color: "from-emerald-700 to-green-900", desc: "Ordene as 10 pragas!" },
  { id: "snake-biblica", name: "Serpente Bíblica", emoji: "🐍", icon: Flame, color: "from-emerald-700 to-lime-900", desc: "Colete itens e cresça sem colidir" },
  { id: "bomberman-biblico", name: "Bomberman Bíblico", emoji: "💥", icon: BombIcon, color: "from-orange-700 to-red-900", desc: "Exploda blocos e vença os inimigos" },
] as const;

export type NewGameId = (typeof gamesCatalog)[number]["id"];
